CREATE DATABASE Armazem;
use Armazem;
CREATE TABLE Produtos(
	COD_PROD INT PRIMARY KEY,
    ID_NF INT,
    ID_ITEM INT,
    VALOR_UNIT DOUBLE,
    QUANTIDADE INT,
    DESCONTO INT NOT NULL
);

SELECT *FROM Produtos;
    
